# Producción - Gunicorn
services:
  django:
    container_name: pti-tekon-rl-cl-django
    build: .
    restart: always
    ports:
      - 8008:8000
    volumes:
      - ./:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
