# Generated by Django 5.0.14 on 2026-02-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_docempresa_link_nextcloud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docempresa',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
