# Generated by Django 5.0.14 on 2026-04-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_alter_docempresa_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocEmpresa',
        ),
    ]
