# Generated by Django 5.0.14 on 2026-04-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docs', '0010_remove_docempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoFinalCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('ultima_actualizacion_ts', models.FloatField(blank=True, help_text='Timestamp Unix de la última modificación en Nextcloud.', null=True)),
                ('ultima_actualizacion', models.CharField(blank=True, help_text='Fecha formateada para mostrar (ej: 14 nov 2025).', max_length=50)),
                ('datos', models.JSONField(help_text='Árbol de carpetas con conteo de archivos.')),
                ('fetched_at', models.DateTimeField(auto_now=True, help_text='Cuándo se actualizó este caché por última vez.')),
            ],
            options={
                'verbose_name': 'Caché Proyecto Final',
                'verbose_name_plural': 'Caché Proyectos Finales',
                'ordering': ['nombre'],
            },
        ),
    ]
