# Generated by Django 5.0.14 on 2026-04-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_add_sitiocache'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstructuraCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100, unique=True)),
                ('datos', models.JSONField(help_text='Lista de carpetas con subfolders vacíos.')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caché Estructura',
                'verbose_name_plural': 'Caché Estructuras',
            },
        ),
    ]
