# Generated by Django 5.0.14 on 2026-04-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_add_estructuracache'),
    ]

    operations = [
        migrations.AddField(
            model_name='estructuracache',
            name='ultima_actualizacion_ts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
