# Generated by Django 5.0.14 on 2026-04-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_estructuracache_add_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Código de empresa tal como aparece en companies.json (ej: AJ, MER).', max_length=100, unique=True)),
                ('link_nextcloud', models.URLField(blank=True, help_text='URL del share de Nextcloud para esta empresa.')),
            ],
            options={
                'verbose_name': 'Link Nextcloud',
                'verbose_name_plural': 'Links Nextcloud',
                'ordering': ['nombre'],
            },
        ),
    ]
