# Generated by Django 5.0.14 on 2026-04-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0015_add_empresalink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.URLField(blank=True, help_text='URL de Nextcloud.')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración del sitio',
                'ordering': ['clave'],
            },
        ),
    ]
