# Generated by Django 5.0.14 on 2026-04-08 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0016_add_siteconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresalink',
            options={'ordering': ['nombre'], 'verbose_name': 'Links Nextcloud Empresa', 'verbose_name_plural': 'Links Nextcloud Empresas'},
        ),
        migrations.RemoveField(
            model_name='empresalink',
            name='link_nextcloud',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='valor',
        ),
        migrations.AddField(
            model_name='empresalink',
            name='link_admin',
            field=models.URLField(blank=True, help_text='URL del share de Nextcloud con permisos de edición (Administrador).'),
        ),
        migrations.AddField(
            model_name='empresalink',
            name='link_visitante',
            field=models.URLField(blank=True, help_text='URL del share de Nextcloud de solo lectura (Visitante).'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='link_admin',
            field=models.URLField(blank=True, help_text='URL del share de Nextcloud con permisos de edición (Administrador).'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='link_visitante',
            field=models.URLField(blank=True, help_text='URL del share de Nextcloud de solo lectura (Visitante).'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('visitante', 'Visitante')], default='visitante', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
