# Generated by Django 5.0.14 on 2026-06-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0017_add_userprofile_and_dual_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'ordering': ['clave'], 'verbose_name': 'Docs Finales', 'verbose_name_plural': 'Docs Finales'},
        ),
    ]
