# Generated by Django 5.0.14 on 2026-06-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0018_alter_siteconfig_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio', models.CharField(max_length=200, unique=True)),
                ('ultima_actualizacion_ts', models.FloatField(blank=True, help_text='Timestamp Unix de la última modificación del subárbol del sitio.', null=True)),
                ('datos', models.JSONField(help_text='Estado calculado: lista de documentos con presente/falta y agregados.')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caché Seguimiento ITO',
                'verbose_name_plural': 'Caché Seguimiento ITO',
                'ordering': ['sitio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoEsperado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('ingenieria', 'Ingeniería'), ('construccion', 'Construcción'), ('recepcion', 'Recepción'), ('otros', 'Otros')], max_length=20)),
                ('actividad', models.CharField(blank=True, max_length=120)),
                ('nombre', models.CharField(help_text='Nombre/código del documento esperado del ITO.', max_length=255)),
                ('responsable_ito', models.CharField(blank=True, help_text='Acción del ITO sobre el documento (ELABORAR/VERIFICAR/FIRMAR).', max_length=30)),
                ('obligatorio', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documento esperado (ITO)',
                'verbose_name_plural': 'Documentos esperados (ITO)',
                'ordering': ['etapa', 'orden', 'nombre'],
                'unique_together': {('etapa', 'nombre')},
            },
        ),
    ]
