# Generated by Django 5.0.14 on 2026-06-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0019_seguimientocache_documentoesperado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoesperado',
            options={'ordering': ['etapa', 'orden', 'nombre'], 'verbose_name': 'Documento esperado', 'verbose_name_plural': 'Documentos esperados'},
        ),
        migrations.RemoveField(
            model_name='documentoesperado',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='documentoesperado',
            name='responsable_ito',
        ),
        migrations.AddField(
            model_name='documentoesperado',
            name='carpeta',
            field=models.CharField(blank=True, help_text='Subcarpeta contenedora (columna CARPETA del xlsx), ej. PLANOS, ABUILT.', max_length=120),
        ),
        migrations.AddField(
            model_name='documentoesperado',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código/nombre del template (columna DOCUMENTO del xlsx).', max_length=255),
        ),
        migrations.AddField(
            model_name='documentoesperado',
            name='rol_buscador',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('FIRMA', 'Firma'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
        migrations.AddField(
            model_name='documentoesperado',
            name='rol_constructor',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('FIRMA', 'Firma'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
        migrations.AddField(
            model_name='documentoesperado',
            name='rol_esp_electrico',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('FIRMA', 'Firma'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
        migrations.AddField(
            model_name='documentoesperado',
            name='rol_ito',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('FIRMA', 'Firma'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
        migrations.AddField(
            model_name='documentoesperado',
            name='rol_ito_hse',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('FIRMA', 'Firma'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
        migrations.AddField(
            model_name='documentoesperado',
            name='rol_tk_redline',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('FIRMA', 'Firma'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
        migrations.AlterField(
            model_name='documentoesperado',
            name='etapa',
            field=models.CharField(choices=[('00_ING._Y_DOC_TECNICA', '00 · Ingeniería y Doc. Técnica'), ('01_HABILITACION_E_INICIO', '01 · Habilitación e Inicio'), ('02_CALIDAD_OOCC', '02 · Calidad OOCC'), ('03_MONTAJE_E_IZAJE', '03 · Montaje e Izaje'), ('04_ELECTRICO', '04 · Eléctrico'), ('05_REP._SUPERVISION', '05 · Rep. Supervisión'), ('06_CIERRE_Y_RECEPCION', '06 · Cierre y Recepción'), ('07_OTROS', '07 · Otros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='documentoesperado',
            name='nombre',
            field=models.CharField(help_text='Nombre del documento esperado.', max_length=255),
        ),
    ]
