# Generated by Django 5.0.14 on 2026-06-20 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0020_alter_documentoesperado_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('sitio', models.CharField(max_length=200)),
                ('rol', models.CharField(help_text="Campo de rol, ej. 'rol_ito' (ver DocumentoEsperado.ROLES).", max_length=20)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='docs.documentoesperado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Confirmación de documento',
                'verbose_name_plural': 'Confirmaciones de documentos',
                'ordering': ['sitio', 'documento', 'rol'],
                'unique_together': {('empresa', 'sitio', 'documento', 'rol')},
            },
        ),
    ]
