# Generated by Django 5.0.14 on 2026-06-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0021_confirmaciondocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoesperado',
            name='tipo_esperado',
            field=models.CharField(blank=True, choices=[('', 'Cualquiera'), ('PDF', 'PDF'), ('DWG', 'DWG / Plano'), ('XLSX', 'Excel'), ('DOCX', 'Word'), ('JPG', 'Imagen')], help_text="Tipo de archivo esperado. 'Presente' = hay ≥1 de este tipo. Vacío = cualquiera.", max_length=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rol_ito',
            field=models.CharField(blank=True, choices=[('rol_buscador', 'Buscador'), ('rol_tk_redline', 'TK Redline'), ('rol_constructor', 'Constructor'), ('rol_ito', 'ITO'), ('rol_ito_hse', 'ITO HSE'), ('rol_esp_electrico', 'Esp. Eléctrico')], help_text='Rol del usuario en la matriz ITO (para auto-confirmar al subir).', max_length=20),
        ),
    ]
