# Generated by Django 5.0.14 on 2026-06-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0022_documentoesperado_tipo_esperado_userprofile_rol_ito'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoesperado',
            name='rol_coordinador',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('FIRMA', 'Firma'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rol_ito',
            field=models.CharField(blank=True, choices=[('rol_buscador', 'Buscador'), ('rol_tk_redline', 'TK Redline'), ('rol_constructor', 'Constructor'), ('rol_ito', 'ITO'), ('rol_ito_hse', 'ITO HSE'), ('rol_esp_electrico', 'Esp. Eléctrico'), ('rol_coordinador', 'Coordinador')], help_text='Rol del usuario en la matriz ITO (para auto-confirmar al subir).', max_length=20),
        ),
    ]
