# Generated by Django 5.0.14 on 2026-06-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0024_asignacionarchivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoNoNecesario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('sitio', models.CharField(max_length=200)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_necesarios', to='docs.documentoesperado')),
            ],
            options={
                'verbose_name': 'Documento no necesario (por sitio)',
                'verbose_name_plural': 'Documentos no necesarios (por sitio)',
                'unique_together': {('empresa', 'sitio', 'documento')},
            },
        ),
    ]
