# Generated by Django 5.0.14 on 2026-06-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0025_documentononecesario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoesperado',
            name='rol_buscador',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
        migrations.AlterField(
            model_name='documentoesperado',
            name='rol_constructor',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
        migrations.AlterField(
            model_name='documentoesperado',
            name='rol_coordinador',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
        migrations.AlterField(
            model_name='documentoesperado',
            name='rol_esp_electrico',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
        migrations.AlterField(
            model_name='documentoesperado',
            name='rol_ito',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
        migrations.AlterField(
            model_name='documentoesperado',
            name='rol_ito_hse',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
        migrations.AlterField(
            model_name='documentoesperado',
            name='rol_tk_redline',
            field=models.CharField(blank=True, choices=[('ELABORAR', 'Elaborar'), ('REVISAR', 'Revisar'), ('VERIFICAR', 'Verificar'), ('FIRMAR', 'Firmar'), ('PRESENTAR', 'Presentar'), ('CONSOLIDAR', 'Consolidar')], max_length=12),
        ),
    ]
