# Generated by Django 5.0.14 on 2026-06-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0030_alter_userprofile_rol_ito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol_ito',
            field=models.CharField(blank=True, choices=[('rol_buscador', 'Buscador'), ('rol_tk_redline', 'TK Redline'), ('rol_constructor', 'Constructora'), ('rol_ito', 'ITO'), ('rol_ito_hse', 'ITO HSE'), ('rol_esp_electrico', 'Eléctrico'), ('rol_coordinador', 'Coordinador')], help_text='Rol del usuario en la matriz ITO (para auto-confirmar al cargar).', max_length=20),
        ),
    ]
