# Generated by Django 5.0.14 on 2026-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0031_alter_userprofile_rol_ito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoesperado',
            name='etapa',
            field=models.CharField(choices=[('00_ING._Y_DOC_TECNICA', '00 · Ingeniería y Doc. Técnica'), ('01_HABILITACION_E_INICIO', '01 · Habilitación e Inicio'), ('02_CALIDAD_OOCC', '02 · Calidad OOCC'), ('03_MONTAJE_E_IZAJE', '03 · Montaje e Izaje'), ('04_ELECTRICO', '04 · Eléctrico'), ('05_REP._SUPERVISION', '05 · Seguimiento'), ('06_CIERRE_Y_RECEPCION', '06 · Cierre y Recepción'), ('07_OTROS', '07 · Otros')], max_length=30),
        ),
    ]
