# Generated by Django 5.0.14 on 2026-06-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0033_alter_documentoesperado_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoITO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('sitio', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Archivo ITO',
                'verbose_name_plural': 'Archivos ITO',
                'ordering': ['path'],
                'unique_together': {('empresa', 'sitio', 'path')},
            },
        ),
    ]
