# Generated by Django 5.0.14 on 2026-06-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0034_archivoito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivoITO',
        ),
    ]
