# Generated by Django 5.0.14 on 2026-06-21 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def consolidar_rol(apps, schema_editor):
    """Consolida en ``rol`` la antigua función ITO (``rol_ito``). Si el usuario tenía una
    función ITO, ese pasa a ser su rol; un 'administrador' sin función → ITO genérico;
    cualquier otro → visitante."""
    UserProfile = apps.get_model("docs", "UserProfile")
    for p in UserProfile.objects.all():
        rol_ito = getattr(p, "rol_ito", "") or ""
        if rol_ito:
            p.rol = rol_ito
        elif p.rol == "administrador":
            p.rol = "rol_ito"
        else:
            p.rol = "visitante"
        p.save(update_fields=["rol"])


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0036_plantillaestructura_sitioestructura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('visitante', 'Visitante'), ('rol_buscador', 'Buscador'), ('rol_tk_redline', 'TK Redline'), ('rol_constructor', 'Constructora'), ('rol_ito', 'ITO'), ('rol_ito_hse', 'ITO HSE'), ('rol_esp_electrico', 'Eléctrico'), ('rol_coordinador', 'Coordinador')], default='visitante', max_length=20),
        ),
        # Migra los datos ANTES de borrar la columna rol_ito.
        migrations.RunPython(consolidar_rol, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userprofile',
            name='rol_ito',
        ),
        migrations.AlterField(
            model_name='documentoesperado',
            name='tipo_esperado',
            field=models.CharField(blank=True, choices=[('', 'Cualquiera'), ('PDF', 'PDF'), ('DWG', 'DWG'), ('XLSX', 'Excel'), ('DOCX', 'Word'), ('JPG', 'Imagen')], help_text="Tipo de archivo esperado. 'Presente' = hay ≥1 de este tipo. Vacío = cualquiera.", max_length=8),
        ),
        migrations.CreateModel(
            name='EliminacionPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('sitio', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eliminación pendiente',
                'verbose_name_plural': 'Eliminaciones pendientes',
                'ordering': ['sitio', 'path'],
                'unique_together': {('empresa', 'sitio', 'path')},
            },
        ),
        migrations.CreateModel(
            name='ObservacionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('sitio', models.CharField(max_length=200)),
                ('rol', models.CharField(help_text='Campo de rol que observó (ver DocumentoEsperado.ROLES).', max_length=20)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='docs.documentoesperado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observación de documento',
                'verbose_name_plural': 'Observaciones de documentos',
                'ordering': ['sitio', 'documento', 'rol'],
                'unique_together': {('empresa', 'sitio', 'documento', 'rol')},
            },
        ),
    ]
