# Generated by Django 5.0.14 on 2026-06-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0037_remove_userprofile_rol_ito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observaciondocumento',
            name='enmendada',
            field=models.BooleanField(default=False, help_text='El autor de la observación marcó que ya fue subsanada (✓ verde).'),
        ),
    ]
