# Generated by Django 5.0.14 on 2026-06-22 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0038_observaciondocumento_enmendada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(help_text='Código de empresa (companies.json).', max_length=100)),
                ('sitio', models.CharField(help_text='Nombre de la carpeta del sitio en Nextcloud.', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitios_permitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a sitio',
                'verbose_name_plural': 'Accesos a sitios',
                'ordering': ['user', 'empresa', 'sitio'],
                'unique_together': {('user', 'empresa', 'sitio')},
            },
        ),
    ]
