# Generated by Django 5.0.14 on 2026-06-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0039_accesositio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='acceso_contratista',
            field=models.BooleanField(default=False, verbose_name='Acceso Docs. Contratista'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='acceso_finales',
            field=models.BooleanField(default=False, verbose_name='Acceso Docs. Finales'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='acceso_seguimiento',
            field=models.BooleanField(default=False, verbose_name='Acceso Seguimiento'),
        ),
    ]
