# Generated by Django 5.0.14 on 2026-06-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0040_userprofile_acceso_contratista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoesperado',
            name='galeria',
            field=models.BooleanField(default=False, help_text='Mostrar los archivos como mosaico de fotos (modal grande). Para documentos tipo registro fotográfico.'),
        ),
    ]
