# Generated by Django 4.2.11 on 2024-03-29 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTICellID', models.CharField(max_length=10, null=True, verbose_name='Codigo Sitio')),
                ('EntelID', models.CharField(max_length=10)),
                ('Nombre', models.CharField(blank=True, max_length=100)),
                ('comuna', models.CharField(blank=True, max_length=30, verbose_name='Comuna')),
                ('Provincia', models.CharField(blank=True, max_length=50)),
                ('altura', models.IntegerField(choices=[(24, '24'), (42, '42'), (48, '48')], default=42, verbose_name='Altura')),
                ('contratista', models.CharField(choices=[('MER', 'MER'), ('AJ', 'AJ')], default='MER', max_length=120, verbose_name='Contratista')),
                ('lat', models.FloatField(blank=True, max_length=11, null=True, verbose_name='Latitud')),
                ('lon', models.FloatField(blank=True, max_length=11, null=True, verbose_name='Longitud')),
                ('ito', models.CharField(max_length=12, verbose_name='ITO')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitios',
            },
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ASG', 'Asignado'), ('EJE', 'Ejecución'), ('TER', 'Terminado'), ('PTG', 'Postergado'), ('CAN', 'Cancelado')], default='EJE', max_length=10, verbose_name='Estado')),
                ('hormigonado', models.BooleanField(default=False, verbose_name='Hor.')),
                ('excavacion', models.BooleanField(default=False, verbose_name='Exc.')),
                ('montado', models.BooleanField(default=False, verbose_name='Mon.')),
                ('empalmeE', models.BooleanField(default=False, verbose_name='Ele.')),
                ('porcentaje', models.FloatField(default=0.0, verbose_name='Porcentaje')),
                ('fechaFin', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha')),
                ('PTICellID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sitio')),
            ],
        ),
    ]
