# Generated by Django 4.2.11 on 2024-03-29 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitio',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.RenameField(
            model_name='avance',
            old_name='PTICellID',
            new_name='sitio',
        ),
        migrations.RenameField(
            model_name='sitio',
            old_name='EntelID',
            new_name='entel_id',
        ),
        migrations.RenameField(
            model_name='sitio',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='sitio',
            old_name='Provincia',
            new_name='provincia',
        ),
        migrations.RenameField(
            model_name='sitio',
            old_name='PTICellID',
            new_name='sitio',
        ),
    ]
