# Generated by Django 4.2.11 on 2024-03-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='lat',
            field=models.FloatField(blank=True, max_length=11, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='lon',
            field=models.FloatField(blank=True, max_length=11, null=True, verbose_name='Longitud'),
        ),
    ]
