# Generated by Django 4.2.11 on 2024-03-29 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sitio_options_rename_pticellid_avance_sitio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitio',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='sitio',
            name='provincia',
        ),
    ]
