# Generated by Django 4.2.11 on 2024-03-29 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_sitio_comuna_remove_sitio_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='sitio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.sitio'),
        ),
    ]
