# Generated by Django 4.2.11 on 2024-03-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_avance_empalmee_alter_avance_excavacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='fechaFin',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Fecha'),
        ),
    ]
