# Generated by Django 4.2.11 on 2024-03-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_avance_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='fechaFin',
            field=models.DateField(blank=True, max_length=19, null=True, verbose_name='Fecha Fin'),
        ),
    ]
