# Generated by Django 4.2.11 on 2024-03-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_avance_fechafin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avance',
            options={'verbose_name': 'Avance', 'verbose_name_plural': 'Avance Proyectos'},
        ),
        migrations.AddField(
            model_name='avance',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
    ]
