# Generated by Django 4.2.11 on 2024-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_avance_options_avance_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, unique=True),
        ),
    ]
