# Generated by Django 4.2.11 on 2024-03-31 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sitio_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitio',
            name='slug',
        ),
    ]
