# Generated by Django 4.2.11 on 2024-04-01 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entel_id', models.CharField(editable=False, max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=10, unique=True)),
                ('sitio', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('descripcion', models.CharField(blank=True, max_length=52, null=True)),
                ('fecha_carga', models.DateField(default=django.utils.timezone.now)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='galeria.galeria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_subidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_carga', models.DateField(default=django.utils.timezone.now)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='galeria.galeria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_subidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
