# Generated by Django 4.2.11 on 2024-03-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_galeria_imagen_delete_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='fecha_carga',
            field=models.DateField(),
        ),
    ]
