# Generated by Django 4.2.11 on 2024-03-25 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_galeria_descripcion_alter_galeria_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='fecha_carga',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
