# Generated by Django 4.2.11 on 2024-03-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_imagen_fecha_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
