# Generated by Django 4.2.11 on 2024-03-31 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sitio_slug'),
        ('galeria', '0006_alter_imagen_descripcion_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='nombre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='main.sitio'),
        ),
    ]
