# Generated by Django 4.2.11 on 2024-03-31 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_alter_galeria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='slug',
        ),
    ]
