# Generated by Django 4.2.11 on 2024-03-31 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_sitio_slug'),
        ('galeria', '0009_galeria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='main.sitio'),
        ),
    ]
