# Generated by Django 4.2.11 on 2024-03-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0012_galeria_descripcion_galeria_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='slug',
            field=models.SlugField(blank=True, max_length=10),
        ),
    ]
