# Generated by Django 4.2.11 on 2024-03-31 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0013_alter_galeria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='slug',
        ),
    ]
