# Generated by Django 4.2.11 on 2024-03-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0015_galeria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
