# Generated by Django 4.2.11 on 2024-03-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0016_alter_galeria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
