# Generated by Django 4.2.11 on 2024-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0017_alter_galeria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, unique=True),
        ),
    ]
