# Generated by Django 4.2.11 on 2024-03-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0019_alter_galeria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='entel_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
