# Generated by Django 4.2.11 on 2024-03-31 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0022_rename_nombre_galeria_sitio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='sitio',
            new_name='nombre',
        ),
    ]
