# Generated by Django 4.2.11 on 2024-03-31 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0023_rename_sitio_galeria_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='nombre',
            new_name='sitio',
        ),
    ]
