# Generated by Django 4.2.11 on 2024-03-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0024_rename_nombre_galeria_sitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
