# Generated by Django 4.2.11 on 2024-04-01 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0027_remove_galeria_user_imagen_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_subidas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
